steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/platinum-snow-374309/mlopsproject', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/platinum-snow-374309/mlopsproject']