steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'triggerDeployment.dockerfile', '-t', 'gcr.io/dtumlops-374214/train_image', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dtumlops-374214/train_image']