steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ultra-complex-374311/train_image', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ultra-complex-374311/train_image']