project: hugging_sweep
program: train_model_sweep.py
method: random
metric:
  goal: maximize
  name: test/accuracy
parameters:
  epochs:
    value: 1
  learning_rate:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.1
  weight_decay:
    values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
  per_device_train_batch_size:
    values: [8,16,64,256]


command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}