name: "flake8 test"

on:
  push:
    branches: [ master, main, Luca-dev ]
  pull_request:
    branches: [ master, main, Luca-dev ]

jobs:
  build:

    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
    - name: Test with pytest
      run: |
        pip install flake8
        pip install black
        black .
        pytest flake8 .